sonar.projectKey=FTurleque_mcp-search-net
sonar.organization=fturleque
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,build/**,coverage/**,target/**,.data/**
sonar.coverage.exclusions=tests/**
sonar.projectVersion=1.1.5
sonar.qualitygate.wait=true
