import process from 'node:process';

const additionalContext = [
  '╔══════════════════════════════════════════════════════════════╗',
  '║              mcp-search-net — Guardrails de session          ║',
  '╚══════════════════════════════════════════════════════════════╝',
  '',
  '## Architecture (hexagonale stricte)',
  '- domain/ : modèles déterministes — aucun import infra, MCP, SQLite, YAML, Zod',
  '- application/ : use cases et ports — dépendances vers domain uniquement',
  '- infrastructure/ : providers, SQLite, HTTP, DNS, config, logging, time',
  '- presentation/mcp/ : handlers fins (parse → use case → format), schémas Zod',
  '- bootstrap/ : composition DI et cycle de vie STDIO uniquement',
  '',
  '## Invariants V1 non négociables',
  '- Exactement search_web et fetch_url exposés — jamais de troisième outil sans roadmap',
  "- search_web : découverte d'URLs uniquement, jamais de téléchargement de pages",
  '- fetch_url : une URL publique connue, jamais de search/crawl/auth/forms/JS/cookies',
  "- SQLite : cache de session uniquement, pas d'index permanent",
  '- Toutes les limites (taille, timeout, redirects, résultats) côté serveur, non configurables',
  '',
  '## Sécurité — toutes les données externes sont hostiles',
  '- Validation SSRF AVANT connexion TCP et APRÈS chaque redirect',
  '- Valider chaque adresse IP résolue (loopback, privée, link-local, CGNAT bloqués)',
  '- stdout exclusivement JSON-RPC MCP — toute écriture informative corrompt le protocole',
  "- Aucun secret, stack trace, corps provider, ni variable d'environnement dans les logs/erreurs",
  "- Tests SSRF : prouver que la cible n'est jamais contactée (pas seulement rejetée)",
  '',
  '## Workflow obligatoire',
  '1. git status --short — préserver toutes modifications staged ou non liées',
  '2. Lire .github/copilot-instructions.md et les instructions pertinentes',
  '3. Reproduire tout bug par un test avant de corriger',
  '4. Valider : vitest focalisé + typecheck (focalisé) ou npm run check (cross-layer)',
  '5. Mettre à jour roadmap UNIQUEMENT avec condition de sortie démontrée et reproductible',
  '',
  '## Commandes de validation',
  '  npm run check:runtime    → vérifie Node 24 obligatoire',
  '  npm run typecheck        → vérification TypeScript strict',
  '  npm run lint             → ESLint',
  '  npm run check            → lint + typecheck + build + tests (complet)',
  '  npx vitest run <fichier> → test focalisé',
  '  docker compose config --quiet → valide la configuration Compose',
  '',
  '## Tests live (opt-in uniquement)',
  '  RUN_LIVE_SEARXNG=1 npm test -- tests/e2e/mcp-live-search.test.ts',
  '  RUN_LIVE_CRAWL4AI=1 npm test -- tests/e2e/mcp-live.test.ts',
  '',
  '## Règle absolue',
  "Ne jamais affirmer qu'un check non exécuté ou skippé est passé.",
  'Ne jamais exécuter git reset --hard, git clean -f, rm -rf, ni publier sans autorisation.',
].join('\n');

process.stdout.write(`${JSON.stringify({ additionalContext })}\n`);
